### GET request to example server
POST http://localhost:4000/patients/create
Content-Type: application/json

{
  "name": "Harish",
  "email": "sss.walker@example.com",
  "address": "4567 Cypress St, Capital City",
  "dateOfBirth": "1977-06-08",
  "registeredDate": "2024-11-28"
}
###
